### ISSUE TITLE
recording csv file issue

### ISSUE THREAD

**Issue by rajbuvana** [chillibasket/processing-grapher#17]
The file can't be opened in csv plotting option. the .csv file saved is not recognised by the program.

**Comment by chillibasket** [comment]
Hi, thanks for reporting the issue. I haven't come across the problem myself yet. Would you be able to provide the following information so that I can replicate the issue:
- What is the version number of the program you are using.
- Did any error message appear when you were trying to open the CSV file.
- Would you be able to upload the CSV file which is causing the issue (if it is too big, you can shorten it by removing rows from the middle of the file).
- Was the CSV file created by the "Live Graph" tab or by an external program?

**Comment by rajbuvana** [comment]
Hi
Thanks for quick response. I am very pleased to run the code to record and view serial output from Triad spectroscopy Sparkfun sensor (18 channels), lot of data at once. I use windows 7 with processing grapher, and the version of code 1.2.2.

I tried to save the data in .csv file. After stopping recording, it says the file saved with data - success.

Then, I tried to open the csv file to graph in the open graph option, it was going to the explorer to open the file, but it could not find the .csv file (combobox listing only comma separated file). Later, I tried to open manually from explorer, and rename the file with .csv extension, because, the file saving option, never allowed me to save in .csv file, as it saves only in text file.

After manually changing the format of the file to .csv, I tried to open in the open graph option with code, it just 'not responding' hang.

I hope, the details are enough now. I will try again.

Regards
Raj

**Comment by rajbuvana** [comment]
Hi
I found the issue now. When it save the file, it only save in .txt format. So, I use the notepad to save the file, back into .csv format. Then open with File Graph, although it won't find the file, I forced to open by typing the file name 'testing.csv.txt' then it open and showed the graph.

Thanks
Raj

**Comment by chillibasket** [comment]
Ok I see where your issue is coming from. There are two ways to save incoming serial data:
- If you start recording in the "Serial" tab, the data will be saved as a text (*.txt) file so that it is possible to save data which is not just numbers.
- If instead you start recording in the "Live Graph" tab, the incoming data will be converted just to numbers and saved as a comma-separated (*.CSV) file.

The "File Graph" tab is only designed to open the second type of data since the first type may contain text which cannot be plotted on the graph.

**Comment by chillibasket** [comment]
I'm going to close this issue as the program is working as expected, however I'll consider ways of improving the interface to help differentiate between the two ways of saving incoming data to avoid this confusion in the future. 

_Note:_ I've just pushed the commit cce27ff93ebb5ae659da7625cdf0271a62d4aa44 which circumvents a bug in the "Data Table" code of the _Processing Core_ which prevented the data from the "Live Graph" and "File Graph" tabs saving correctly. While not directly related to this issue, it may have contributed to the confusion.
