### ISSUE TITLE
Reading from the port is not functioning properly.

### ISSUE THREAD

**Issue by dd777mine** [chillibasket/processing-grapher#35]
Hello! I need help. No matter how much I try, I can't get your program to read data from the port properly. The problem is that, firstly, she does not see any streaming incoming data, and secondly, she cannot even be responsible for the messages that I send through her to the microcontroller (NodeMCU V3 ESP8266). At the same time, everything in the Arduino IDE in the plotter and port monitor works flawlessly. I used the code from the documentation and even tried to run the program through the Processing IDE version that was listed in the documentation. True, if you quickly click on the Connect\Disconnect button, then some data sometimes appears. But it's a one time thing. I also tried to run everything on different computers, but all to no avail.
![Screenshot_1](https://user-images.githubusercontent.com/26344829/229937493-c0c27dd9-2929-4691-b2eb-dce22720e6e3.png)
![Screenshot_2](https://user-images.githubusercontent.com/26344829/229937517-0dad9f66-a9b8-4aa1-b301-0c0cb5b28f4a.png)
![Screenshot_3](https://user-images.githubusercontent.com/26344829/229937528-1bf2aabf-1996-47a5-adde-a67144991716.png)
![Screenshot_13](https://user-images.githubusercontent.com/26344829/229937574-a3ae7276-8782-4653-93d0-eb2c59d7752c.png)
![Screenshot_232](https://user-images.githubusercontent.com/26344829/229937605-a99c2b76-abcc-4aae-b1ef-acaa8ba0a776.png)

**Comment by chillibasket** [comment]
The program is working fine for me using an Arduino Uno and also a Teensy 3.6. The issue you are seeing is probably specific to your application using the NodeMCU V3 ESP8266. Here are some things to try in order to figure out what could be causing the problem:
- If you run the program through the Processing IDE, do any errors appear in the console at the bottom of the IDE? 
- In the Grapher program, click on the settings icon on the top-right and try switching the "Line Ending" option between "New Line" and "Carriage Return". Do either of these options work?
- In the Processing IDE in the file "ProcessingGrapher.pde", try changing line 218 from `final String activeRenderer = FX2D;` to `final String activeRenderer = JAVA2D;`

**Comment by chillibasket** [comment]
Closing this thread as I can't replicate the issue and haven't received any more information
